---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: oracle-xe
  labels:
    name: oracle-xe
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        name: oracle-xe
    spec:
      containers:
      - name: oracle-xe
        image: sath89/oracle-xe-11g

        ports:
        - name: oracle-xe
          containerPort: 1521
