---
apiVersion: v1
kind: Service
metadata:
  name: oracle-xe
  labels:
    name: oracle-xe
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
  - port: 31521
    targetPort: 1521
  selector:
    name: oracle-xe
