apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    field.cattle.io/creatorId: user-vxmgg
    field.cattle.io/publicEndpoints: '[{"addresses":["42.62.83.2"],"port":30261,"protocol":"TCP","serviceName":"default:oracle-v2-nodeport","allNodes":true},{"addresses":["42.62.83.2"],"port":31021,"protocol":"TCP","serviceName":"default:oracle-v2-nodeport","allNodes":true}]'
  generation: 2
  labels:
    workload.user.cattle.io/workloadselector: deployment-default-oracle-xe
  name: oracle-xe
  namespace: default
  resourceVersion: "1359395"
  selfLink: /apis/apps/v1beta2/namespaces/default/deployments/oracle-xe
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-oracle-xe
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        field.cattle.io/ports: '[[{"containerPort":1521,"dnsName":"oracle-xe-nodeport","kind":"NodePort","name":"1521tcp01","protocol":"TCP","sourcePort":0},{"containerPort":8080,"dnsName":"oracle-xe-nodeport","kind":"NodePort","name":"8080tcp01","protocol":"TCP","sourcePort":0}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-oracle-xe
    spec:
      affinity: {}
      containers:
      - image: sath89/oracle-xe-11g
        imagePullPolicy: Always
        name: oracle-xe
        ports:
        - containerPort: 1521
          name: 1521tcp01
          protocol: TCP
        - containerPort: 8080
          name: 8080tcp01
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /u01/app/oracle
          name: vol1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /my/oracle/data
          type: DirectoryOrCreate
        name: vol1
