---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tomcat
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        name: tomcat
    spec:
      containers:
      - env:
        - name: DATABASE
          value: oracle-xe
      - name: tomcat
        image: tomcat
        ports:
       - containerPort: 8080
